# Generated by Django 4.2.5 on 2023-09-24 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.IntegerField(default=100, verbose_name='стоимость товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='category',
            name='describe',
            field=models.TextField(verbose_name='описание категории'),
        ),
    ]
