# Generated by Django 4.2.5 on 2023-10-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.TextField(default=20, verbose_name='создана для отката'),
            preserve_default=False,
        ),
    ]
